<a href="https://colab.research.google.com/github/CodyHuff/Data-Science/blob/main/Cody_Huff_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [1]:
for i in range(100): #loop counts to 100
    print(i) #prints loop

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [2]:
for i in range(5,8): #loop that goes from 5 to 8
    print(i) #prints the loop

5
6
7


In [3]:
for i in range(3): #loop goes from 0 to 4
    print( "Test Number: " , i ) #prints the numbers with "test number"

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [5]:
def square(x): #enables python function
    return x**2

In [6]:
square(5) #will give us 5 squared

25

In [7]:
square(square(2)) #squares the squaring function

16

In [ ]:
square(square(square(2))) #squares the squaring function twice


256

In [ ]:
square(123456) #squares the number

15241383936

In [ ]:
square(square(5)) #squares the squaring function

625

In [ ]:
def add_two(x): #enables python function
    return x+2 #function will add 2 to given number

In [ ]:
add_two(5) #adds 2 to 5

7

In [ ]:
square(add_two(5)) #adds 2 to 5 then squares it

49

### Logical Branching

In [8]:
choice = "apple" #makes the choice equal to apple

In [9]:
if choice == "apple": #saying if choice is apple the functions below will apply to it

    print("You choose apples.") #this will be printed

else: #if conditions are not met
    
    print("You did not choose apples.") #this will be printed

You choose apples.


In [11]:
choice = "orange" #makes the choice orange

In [12]:
if choice == "apple": #if the choice equals apple

    print("You choose apples.") #this will be printed

else: #if conditions are not met
    
    print("You did not choose apples.") #this will be printed

You did not choose apples.


In [15]:
choice = "apple" #choice is apple

In [14]:
if choice == "apple": #if choice equals apple 

    print("You choose apples.")  #this all will be printed
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange": #if choice equals orange

    print("You choose oranges.") #these will be printed
    print("Thank you, shop again!")

else: #if neither are choice this will print below
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [16]:
choice = input("Please enter your choice (i.e. apple): ") #asks for choice to be stored

Please enter your choice (i.e. apple): apple


In [17]:
choice #stored variable

'apple'

In [18]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [67]:
np.random.random()

0.23938667371796452

In [68]:
np.random.random() > 0.5

False

In [69]:
def flip_coin(): 
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [72]:
flip_coin() #coin is flipped randomly

Heads


### Graphics Output

In [33]:
from IPython.core.display import display, HTML #inputs python function

In [35]:
display(HTML('<h1>Hello, world!</h1>')) #displays the "hello world"

In [36]:
def coin():
  return np.random.randint(2)

In [38]:
coin()

0

In [44]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #displays coin

In [43]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #inputs what heads would look like
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'  #INputs what tails woild look like

In [45]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [48]:
show_img(heads) #displays heads

In [49]:
show_img(tails) #displays tails

In [50]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [58]:
flip_coin() #flips coin to either heads or tails

In [62]:
for i in range(5): #displays 5 coins that could either be hheads or tails
    flip_coin()

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [63]:
def shuffle(x): #imports shuffle function
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [64]:
a = np.arange(52) #the range is out of 52

In [65]:
shuffle(a) #cards shuffled randomly

array([ 8,  0, 27, 37, 47, 23, 36, 43, 41, 39,  4,  6, 14, 35,  5, 33, 29,
       48, 20, 16,  1, 11,  2, 22, 42,  7, 25, 13,  3, 21, 50, 15, 24, 12,
       26,  9, 45, 51, 34, 19, 30, 28, 40, 46, 38, 44, 31, 18, 10, 49, 17,
       32])

In [66]:
np.random.permutation(52)

array([ 8, 47,  2, 27, 19, 14, 12, 35, 31, 37, 29,  6, 45, 42, 46, 16, 38,
       33, 22, 48, 50, 28, 51, 13,  0, 24, 43, 34, 30, 25, 23, 44,  7, 10,
       36,  4,  3, 20,  9, 39, 21, 41, 18, 40, 17, 49, 32, 15, 26, 11,  5,
        1])

### Speed Test

In [ ]:
%%timeit
shuffle(a)

In [ ]:
%%timeit
np.random.permutation(52)

In [20]:
import numpy as np #imports numpy libray

In [21]:
np.random.permutation(52) #gives random order out of 52

array([15,  6, 37, 38, 34, 13, 49,  9, 18,  7, 44, 47,  4, 33, 41,  1, 26,
       42, 17, 35, 39, 27, 28, 20, 21, 22, 46, 23, 51, 36, 19, 25, 30, 16,
        5, 12,  0,  2, 24, 31,  8,  3, 11, 43, 50, 48, 10, 29, 45, 14, 40,
       32])

In [22]:
cards = np.random.permutation(52) #keeps permutation of cards

In [ ]:
cards

array([32,  0, 51, 29, 27, 15, 39, 45, 42, 12, 30, 28, 44, 34, 33, 16, 49,
       47,  6, 22, 40, 24, 10, 21, 11, 23, 41, 48,  5, 36, 13, 46, 31, 17,
        7, 14,  1, 26,  2, 43, 25,  4, 35, 18,  8, 37, 50,  9,  3, 38, 20,
       19])

In [23]:
cards[0]

23

In [24]:
cards[1]

10

In [25]:
cards[2]

40

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [26]:
np.arange(52).reshape(4,13) #sets array in correct order

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [27]:
np.arange(52).reshape(4,13)%13 #makes 13 the remainder

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [28]:
np.arange(52).reshape(4,13)//13 #divides by 13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [29]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #creates character strings
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [30]:
def card_name(card_number): 
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [31]:
card_name(0) #writes the card in the deck based on its order 

'Ace of Clubs'

In [32]:
card_name(51)

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) #stores permutation

In [ ]:
top_of_deck         = card_name(cards[0]) #makes seperate variablethat shows the full name of specific card in array
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck #shows 

('Three of Hearts', 'Nine of Diamonds', 'Ten of Hearts')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

Four of Spades
Six of Diamonds
Ace of Diamonds
Eight of Clubs
Three of Diamonds


In [ ]:
for i in range(15):
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(0, 11)

In [ ]:
suit[i]

'k'

In [ ]:
card[j]

'q'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [ ]:
show_img(img)

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3)

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img) #displays image

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)