<a href="https://colab.research.google.com/github/CodyHuff/Data-Science/blob/main/CodyHuffLab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loops

In [2]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
for i in range(100):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [6]:
for i in range(5,8):
  print(i)

5
6
7


In [7]:
for i in range(3):
  print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


#Functions

In [8]:
def square(x):
  return x**2

In [9]:
square(5)

25

In [10]:
square(6)

36

In [11]:
square(7937940)

63010891443600

In [13]:
square(square(2))

16

In [16]:
square(square(4))

256

In [17]:
def add_two(x):
  return x+2

In [18]:
add_two(5)

7

In [28]:
choice="apple"

In [24]:
if choice=="apple":

  print("You choose apples.")

else:

  print("You did not choose apples.")



You did not choose apples.


In [29]:
choice="orange"

In [32]:
if choice=="apple":

  print("You choose apples.")

elif choice == "orange":

  print("You choose oranges.")

else:

  print("You did not choose apples or oranges.")

You choose oranges.


In [33]:
if choice=="apple":

  print("You choose apples.")

elif choice == "orange":

  print("You choose oranges.")

else:

  print("You did not choose apples or oranges.")

You choose oranges.


In [27]:
if choice=="apple":

  print("You choose apples.")

elif choice == "orange":

  print("You choose oranges.")

else:

  print("You did not choose apples or oranges.")

You choose oranges.


#User Input

In [36]:
choice= input("Please enter your choice (i.e. apple):")

Please enter your choice (i.e. apple):apple


In [37]:
choice

'apple'

In [38]:
choice= input("Please enter your choice (i.e. apple):")

Please enter your choice (i.e. apple):oranges


In [39]:
choice

'oranges'

#Cards

In [40]:
import numpy as np

In [41]:
np.random.permutation(52)

array([ 9, 34, 16, 51, 44, 20, 27, 21, 19,  4, 11, 33,  3, 39, 30, 45, 50,
       23, 38, 43,  5, 10, 13, 12,  7, 37, 41, 47, 25, 14, 49, 29, 42, 24,
       15,  0, 36,  8, 46, 26, 22, 31, 48,  6, 40, 17, 35, 18,  1, 32, 28,
        2])

In [ ]:
np.random.permutation(52)

array([ 9, 34, 16, 51, 44, 20, 27, 21, 19,  4, 11, 33,  3, 39, 30, 45, 50,
       23, 38, 43,  5, 10, 13, 12,  7, 37, 41, 47, 25, 14, 49, 29, 42, 24,
       15,  0, 36,  8, 46, 26, 22, 31, 48,  6, 40, 17, 35, 18,  1, 32, 28,
        2])

In [42]:
cards = np.random.permutation(52)

In [43]:
cards

array([22,  4,  8, 19, 50, 35, 16, 49, 15,  3, 26, 10, 29,  7, 47, 27, 24,
       23, 36, 44, 51, 48, 13, 30, 34,  5, 42,  0, 38, 18, 28, 21, 12, 14,
       40, 45, 41, 25, 17, 33,  9, 43, 39, 37, 11, 46,  1,  6, 31,  2, 20,
       32])

In [44]:
cards[0]

22

In [45]:
cards[1]

4

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [48]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [49]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [50]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [51]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [58]:
def card_name(card_number):

    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [59]:
card_name(0)

'Ace of Clubs'

In [60]:
card_name(51)

'King of Diamonds'

In [61]:
cards = np.random.permutation(52)

In [62]:
top_of_deck           =card_name(cards[0])
second_card_in_deck   =card_name(cards[1])
last_card_in_deck     =card_name(cards[-1])

In [63]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Jack of Hearts', 'Queen of Spades', 'Seven of Diamonds')

In [64]:
for i in range(5):
    print(card_name(cards[i]))

Jack of Hearts
Queen of Spades
Three of Diamonds
Eight of Clubs
Six of Diamonds


In [65]:
for i in range(5):
    print(card_name(cards[i]))

Jack of Hearts
Queen of Spades
Three of Diamonds
Eight of Clubs
Six of Diamonds


In [66]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [68]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [102]:
i = np.random.randint(4)
j = np.random.randint(13)

In [103]:
i,j

(1, 0)

In [104]:
i,j

(1, 0)

In [105]:
suit[i]

'p'

In [106]:
card[j]

'a'

In [107]:
from IPython.core.display import display, HTML

In [108]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [109]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [110]:
show_img(img)